import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/features/Login'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1>Hello, lisarnjs!</h1>
        <Login />
      </div>
    </div>
  )
}

export default Home
